server:
  port: 8080
spring:
  jackson:
    serialization:
      indent_output: true
  datasource:
    url: 'jdbc:postgresql://localhost:5432/generic'
    username: 'postgres'
    password: 'root'
    hikari:
      catalog: 'public'
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: true
    properties:
      hibernate:
        default_schema: 'public'
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
    hibernate:
      ddl-auto: update
  main:
    allow-bean-definition-overriding: true
  sql:
    init:
      platform: postgres